name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  DOCKER_IMAGE: your-docker-username/your-app-name
  DOCKER_TAG: ${{ github.sha }}
  CONTAINER_PORT: 3000
  HOST_PORT: 3000

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22.x'
        cache: 'yarn'
    
    - name: Install Yarn
      run: corepack enable && yarn set version stable
    
    - name: Install production dependencies
      run: yarn install --production --frozen-lockfile
    
    - name: Lint
      run: yarn lint
    
    - name: Run tests
      run: yarn test
    
    - name: Build
      run: yarn build

  deploy:
    needs: test
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: ${{ github.ref == 'refs/heads/main' }}
        tags: |
          ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}
          ${{ env.DOCKER_IMAGE }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Deploy to production
      if: github.ref == 'refs/heads/main'
      run: |
        # Add your deployment commands here
        # Example: ssh into server and run docker-compose up -d
        echo "Deploying to production..."
    
    - name: Deploy to staging
      if: github.ref == 'refs/heads/develop'
      run: |
        # Add your staging deployment commands here
        echo "Deploying to staging..."
